// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjlrmldzqxiafnludntl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbHJtbGR6cXhpYWZubHVkbnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDkyMzMsImV4cCI6MjA2ODMyNTIzM30.ConP5A6RVqtHHHPvYeQl2uMJxmRcszNZ9ChyDgp0-bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});